### ISSUE TITLE
Example request and response JSON objects? [Documentation]

### ISSUE THREAD

**Issue by mepc36** [ashleykleynhans/audiocraft-docker#2]
I'm looking to run audiocraft as a RESTful API. Do you have any example request & response JSON objects? Or does audiocraft not come prepackaged as a web service? I looked through the code but I'm a JavaScript guy, not Python, so I still can't really tell. Thank you!

EDIT: If this is an issue better saved for the parent `audiocraft` repo please let me know and apologies.

**Comment by ashleykleynhans** [comment]
The upstream audiocraft project basically provides a Python Gradio Web UI for you to interact with the model(s), it does not provide any kind of API.

This project provides a Docker container so that you can run audiocraft on RunPod GPU Cloud pods if you don't have a GPU available to run it locally, it does not provide any kind of API.

If you are interested in an API, then the best approach would most likely be to port this project as well as the upstream audiocraft project to be able to run as a RunPod Serverless worker and then you can create a RunPod Serverless Endpoint and send API requests to that endpoint.

**Comment by mepc36** [comment]
Good idea, thanks Ashley!

**Comment by mepc36** [comment]
I will probably try to get it running as a Flask server, since I'm familiar with that pattern since that's what Riffusion uses:

https://github.com/riffusion/riffusion

I will drop another note on this thread if I ever follow through. Closing! Thanks again
